In [1]:
import pandas as pd
import sklearn.preprocessing as preproc
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
ct_df = pd.read_csv('/content/county-election.csv', sep=';')
#ct_df['County'] = ct_df['County'].apply(lambda x:x.split()[0])
ct_df = ct_df[['State','County', 'Adult.smoking', 'Median Earnings 2010', 'Violent.crime']]
ct_df.head()


State                       County  ...  Median Earnings 2010  Violent.crime
0     Georgia         Pike County, Georgia  ...          28673.490475          59.74
1        Utah         Wasatch County, Utah  ...          28934.628255          57.80
2  Washington  Franklin County, Washington  ...          22461.965715         293.21
3    Nebraska     Madison County, Nebraska  ...          24901.171745         125.91
4     Florida         Gulf County, Florida  ...          25476.323810         392.90

[5 rows x 5 columns]

In [2]:
cv_df = pd.read_csv('/content/time_series_covid19_confirmed_US.csv',sep=',')
cv_df.head()

UID iso2 iso3  code3  ...  10/28/21 10/29/21 10/30/21 10/31/21
0  84001001   US  USA    840  ...     10219    10228    10239    10252
1  84001003   US  USA    840  ...     37350    37372    37398    37414
2  84001005   US  USA    840  ...      3596     3596     3599     3601
3  84001007   US  USA    840  ...      4275     4276     4278     4279
4  84001009   US  USA    840  ...     10364    10371    10395    10406

[5 rows x 660 columns]

In [3]:
cv_df['County'] = cv_df['Admin2']+' County, '+cv_df['Province_State']
cv_df['Total Confirmed']=cv_df['10/31/21']
cv_df=cv_df[['County','Total Confirmed']]
cv_df.head()


County  Total Confirmed
0  Autauga County, Alabama            10252
1  Baldwin County, Alabama            37414
2  Barbour County, Alabama             3601
3     Bibb County, Alabama             4279
4   Blount County, Alabama            10406

In [4]:
df = pd.merge(cv_df, ct_df, on='County', how='left')
df.head()

County  ...  Violent.crime
0  Autauga County, Alabama  ...         302.91
1  Baldwin County, Alabama  ...         213.30
2  Barbour County, Alabama  ...         154.33
3     Bibb County, Alabama  ...         254.24
4   Blount County, Alabama  ...         164.46

[5 rows x 6 columns]

In [5]:
ca_df= pd.read_csv('/content/county-vaccination.csv')
ca_df.head()

Date  FIPS  ... series_complete_65PlusPop_pct_UR_Equity metro_status
0  2021/10/31  1001  ...                                     3.0        Metro
1  2021/10/31  1003  ...                                     4.0        Metro
2  2021/10/31  1005  ...                                     7.0    Non-metro
3  2021/10/31  1007  ...                                     3.0        Metro
4  2021/10/31  1009  ...                                     3.0        Metro

[5 rows x 33 columns]

In [6]:
ca_df['County']=ca_df['County']+', '+ca_df['StateName']
ca_df['vaccination_percentage_12+']=ca_df['Series_Complete_12PlusPop_Pct']
ca_df=ca_df[['County','vaccination_percentage_12+']]
ca_df.head()


County  vaccination_percentage_12+
0  Autauga County, Alabama                        42.0
1  Baldwin County, Alabama                        51.6
2  Barbour County, Alabama                        44.5
3     Bibb County, Alabama                        35.6
4   Blount County, Alabama                        32.9

In [7]:
df = pd.merge(ca_df, df, on='County', how='left')
df.head()

County  ...  Violent.crime
0  Autauga County, Alabama  ...         302.91
1  Baldwin County, Alabama  ...         213.30
2  Barbour County, Alabama  ...         154.33
3     Bibb County, Alabama  ...         254.24
4   Blount County, Alabama  ...         164.46

[5 rows x 7 columns]

In [8]:
cb_df= pd.read_csv('/content/us_county.csv', encoding='ISO-8859-1')
cb_df.head()

fips          county    state  ... female_percentage        lat       long
0  1001  Autauga County  Alabama  ...         51.315217  32.534923 -86.642730
1  1003  Baldwin County  Alabama  ...         51.376936  30.727479 -87.722564
2  1005  Barbour County  Alabama  ...         46.873788  31.869581 -85.393210
3  1007     Bibb County  Alabama  ...         46.055844  32.998628 -87.126475
4  1009   Blount County  Alabama  ...         50.673953  33.980869 -86.567380

[5 rows x 11 columns]

In [9]:
cb_df['County'] = cb_df['county']+', '+cb_df['state']
cb_df=cb_df[['County','median_age','population','female_percentage']]
cb_df.head()

County  median_age  population  female_percentage
0  Autauga County, Alabama        37.8       55200          51.315217
1  Baldwin County, Alabama        42.8      208107          51.376936
2  Barbour County, Alabama        39.9       25782          46.873788
3     Bibb County, Alabama        39.9       22527          46.055844
4   Blount County, Alabama        40.8       57645          50.673953

In [10]:
df = pd.merge(df, cb_df, on='County', how='left')
df.head()

County  ...  female_percentage
0  Autauga County, Alabama  ...          51.315217
1  Baldwin County, Alabama  ...          51.376936
2  Barbour County, Alabama  ...          46.873788
3     Bibb County, Alabama  ...          46.055844
4   Blount County, Alabama  ...          50.673953

[5 rows x 10 columns]

In [11]:
cc_df= pd.read_csv('/content/counties_dataset.csv', encoding='ISO-8859-1')
cc_df.head()

FIPS    State       Area_Name  ...  LARCENY  MOTOR VEHICLE THEFTS  ARSON
0  1001  Alabama  Autauga County  ...   1233.0                  85.0  108.0
1  1003  Alabama  Baldwin County  ...   3829.0                 192.0   31.0
2  1005  Alabama  Barbour County  ...    362.0                  21.0    0.0
3  1007  Alabama     Bibb County  ...    251.0                  27.0    0.0
4  1009  Alabama   Blount County  ...    865.0                  86.0    9.0

[5 rows x 347 columns]

In [12]:
cc_df['County'] = cc_df['Area_Name']+', '+cc_df['State']
cc_df['high school diploma rate']=cc_df['Percent of adults with a high school diploma only 2014-18']
cc_df=cc_df[['County','high school diploma rate','Total Hospitals (2019)','Total Primary Care Physicians (2019)','Total Specialist Physicians (2019)','Median_Household_Income_2018','Unemployment_rate_2018']]
cc_df.head()

County  ...  Unemployment_rate_2018
0  Autauga County, Alabama  ...                     3.6
1  Baldwin County, Alabama  ...                     3.6
2  Barbour County, Alabama  ...                     5.2
3     Bibb County, Alabama  ...                     4.0
4   Blount County, Alabama  ...                     3.5

[5 rows x 7 columns]

In [13]:
df = pd.merge(df, cc_df, on='County', how='left')
df.head()

County  ...  Unemployment_rate_2018
0  Autauga County, Alabama  ...                     3.6
1  Baldwin County, Alabama  ...                     3.6
2  Barbour County, Alabama  ...                     5.2
3     Bibb County, Alabama  ...                     4.0
4   Blount County, Alabama  ...                     3.5

[5 rows x 16 columns]

In [14]:
df = df.drop_duplicates(subset=['County'])
df = df.dropna()
df.head()

County  ...  Unemployment_rate_2018
0  Autauga County, Alabama  ...                     3.6
1  Baldwin County, Alabama  ...                     3.6
2  Barbour County, Alabama  ...                     5.2
3     Bibb County, Alabama  ...                     4.0
4   Blount County, Alabama  ...                     3.5

[5 rows x 16 columns]

In [15]:
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
!pip install xgboost
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier
from sklearn import neighbors
models = [Perceptron(), 
          LogisticRegression(C=1000.0, random_state=0), 
          SVC(kernel='linear', C=1.0), 
          SVC(kernel='rbf',gamma=0.2,C=0.5),
          MLPClassifier(activation='relu', solver='adam', alpha=0.0001),
          neighbors.KNeighborsClassifier(n_neighbors=5, n_jobs=1),
          DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0),
          RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=1, n_jobs=2),
          XGBClassifier(n_estimators=200, use_label_encoder=False, max_depth=4, learning_rate=0.1)
         ]

model_names = ['Perceptron','LogisticRegression','Linear-SVM','No-linear-SVM','neural_network','KNN', 'DecisionTreeClassifier', 'RandomForest', 'XGBOOST']

# **Case1:The risk is measured by the total number of infections in a country.**

In [16]:
df['risk'] = df['Total Confirmed'].apply(lambda x: 0 if x<df['Total Confirmed'].mean() else 1)
x = df[['Adult.smoking', 'Median Earnings 2010', 'Violent.crime','vaccination_percentage_12+','median_age','female_percentage','high school diploma rate','Total Hospitals (2019)','Total Primary Care Physicians (2019)','Total Specialist Physicians (2019)','Median_Household_Income_2018','Unemployment_rate_2018']]
y = df['risk']
x = np.array(x)
y = np.array(y)

X_train, X_test, y_train, y_test= train_test_split(
    x, y,test_size=0.2, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler() 

sc.fit(X_train)

print(sc.scale_, sc.mean_)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
X_train_std[0]

[6.25130192e-02 4.94895975e+03 1.96201081e+02 1.38820130e+01
 5.01331924e+00 2.06377750e+00 7.32422521e+00 4.61360770e+00
 5.56359945e+02 6.11731338e+02 1.40962601e+04 1.30300791e+00] [2.13314891e-01 2.57453228e+04 2.54026918e+02 5.24332472e+01
 4.13324199e+01 5.00574099e+01 3.42706825e+01 1.89079444e+00
 1.79004320e+02 1.95290345e+02 5.34876086e+04 4.06142709e+00]


array([-0.69289393, -0.30277325,  0.37911657, -2.75415728, -0.92402251,
        0.25500503,  0.83685541, -0.36492815, -0.28958139, -0.28937596,
       -1.15467567,  0.64356701])

In [17]:
df['risk'].value_counts()

0    1941
1     477
Name: risk, dtype: int64

In [18]:
t=0
for i in y_test:
  if i==0: t=t+1
print(t)

367


In [19]:
from sklearn import metrics
from sklearn.metrics import roc_curve, auc, roc_auc_score
def train_and_get_importance(model, model_name):
    print(model_name+'----traning')
    model.fit(X_train_std,y_train)
    y_pred = model.predict(X_test_std)
    print('Misclassified samples: %d' % (y_test != y_pred).sum())
    from sklearn.metrics import accuracy_score
    print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
    print(metrics.classification_report(y_test, y_pred, target_names=['0', '1']))
    con_mat=metrics.confusion_matrix(y_test, y_pred)
    print(con_mat)
    false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
    print ('auc score', auc(false_positive_rate, true_positive_rate))
    try:
        feature = model.feature_importances_
        print('feature importances are:')
        feature_name = ['Adult.smoking', 'Median Earnings 2010', 'Violent.crime','vaccination_percentage_12+','median_age','female_percentage','high school diploma rate','Total Hospitals (2019)','Total Primary Care Physicians (2019)','Total Specialist Physicians (2019)','Median_Household_Income_2018','Unemployment_rate_2018']
        for i in  range(len(feature)):
            print(feature_name[i],':',feature[i])
        most_impotant = feature_name[np.argmax(feature)]
        print('for {}, the most important feature is "{}"'.format(model_name,  most_impotant))
    except:
        pass
    print('------------------------------------------------------------------------')
    
for model, model_name in zip(models, model_names):
    train_and_get_importance(model, model_name)


Perceptron----traning
Misclassified samples: 44
Accuracy: 0.91
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       367
           1       0.82      0.80      0.81       117

    accuracy                           0.91       484
   macro avg       0.88      0.87      0.88       484
weighted avg       0.91      0.91      0.91       484

[[346  21]
 [ 23  94]]
auc score 0.8730990474859684
------------------------------------------------------------------------
LogisticRegression----traning
Misclassified samples: 21
Accuracy: 0.96
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       367
           1       0.91      0.91      0.91       117

    accuracy                           0.96       484
   macro avg       0.94      0.94      0.94       484
weighted avg       0.96      0.96      0.96       484

[[356  11]
 [ 10 107]]
auc score 0.9422785812431588
-----------------------------------

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


Misclassified samples: 17
Accuracy: 0.96
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       367
           1       0.92      0.94      0.93       117

    accuracy                           0.96       484
   macro avg       0.95      0.96      0.95       484
weighted avg       0.97      0.96      0.97       484

[[357  10]
 [  7 110]]
auc score 0.9564614918838352
------------------------------------------------------------------------
KNN----traning
Misclassified samples: 41
Accuracy: 0.92
              precision    recall  f1-score   support

           0       0.93      0.96      0.95       367
           1       0.87      0.77      0.81       117

    accuracy                           0.92       484
   macro avg       0.90      0.87      0.88       484
weighted avg       0.91      0.92      0.91       484

[[353  14]
 [ 27  90]]
auc score 0.8655418151330957
------------------------------------------------------------------------

# **Case 2:The risk is measured by the total number of infections/ total population in a country.**

In [35]:
o=df['Total Confirmed'].sum()
p=df['population'].sum()
q=o/p
print(o,p,q)

42613707.0 304500732.0 0.13994615618855064


In [36]:
df['a']=df['Total Confirmed']/df['population']
#df['risk2'] = df['a'].apply(lambda x: 0 if x<df['a'].mean() else 1)
df['risk2'] = df['a'].apply(lambda x: 0 if x<q else 1)
df.head()

County  vaccination_percentage_12+  ...         a risk2
0  Autauga County, Alabama                        42.0  ...  0.185725     1
1  Baldwin County, Alabama                        51.6  ...  0.179783     1
2  Barbour County, Alabama                        44.5  ...  0.139671     0
3     Bibb County, Alabama                        35.6  ...  0.189950     1
4   Blount County, Alabama                        32.9  ...  0.180519     1

[5 rows x 19 columns]

In [37]:
df['risk2'].value_counts()

1    1504
0     914
Name: risk2, dtype: int64

In [38]:
y2=df['risk2']
y2=np.array(y2)
X2_train, X2_test, y2_train, y2_test= train_test_split(
    x, y2,test_size=0.2, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

sc.fit(X2_train)

print(sc.scale_, sc.mean_)

X2_train_std = sc.transform(X2_train)
X2_test_std = sc.transform(X2_test)
X2_train_std[0]

[6.25130192e-02 4.94895975e+03 1.96201081e+02 1.38820130e+01
 5.01331924e+00 2.06377750e+00 7.32422521e+00 4.61360770e+00
 5.56359945e+02 6.11731338e+02 1.40962601e+04 1.30300791e+00] [2.13314891e-01 2.57453228e+04 2.54026918e+02 5.24332472e+01
 4.13324199e+01 5.00574099e+01 3.42706825e+01 1.89079444e+00
 1.79004320e+02 1.95290345e+02 5.34876086e+04 4.06142709e+00]


array([-0.69289393, -0.30277325,  0.37911657, -2.75415728, -0.92402251,
        0.25500503,  0.83685541, -0.36492815, -0.28958139, -0.28937596,
       -1.15467567,  0.64356701])

In [39]:
t=0
for i in y2_test:
  if i==0: t=t+1
print(t)

169


In [40]:


def train_and_get_importance2(model, model_name):
    print(model_name+'----traning')
    model.fit(X2_train_std,y2_train)
    y2_pred = model.predict(X2_test_std)
    print('Misclassified samples: %d' % (y2_test != y2_pred).sum())
    from sklearn.metrics import accuracy_score
    print('Accuracy: %.2f' % accuracy_score(y2_test, y2_pred))
    print(metrics.classification_report(y2_test, y2_pred, target_names=['0', '1']))
    con_mat=metrics.confusion_matrix(y2_test, y2_pred)
    print(con_mat)
    false_positive_rate, true_positive_rate, thresholds = roc_curve(y2_test, y2_pred)
    print ('auc score', auc(false_positive_rate, true_positive_rate))
    try:
        feature = model.feature_importances_
        print('feature importances are:')
        feature_name = ['Adult.smoking', 'Median Earnings 2010', 'Violent.crime','vaccination_percentage_12+','median_age','female_percentage','high school diploma rate','Total Hospitals (2019)','Total Primary Care Physicians (2019)','Total Specialist Physicians (2019)','Median_Household_Income_2018','Unemployment_rate_2018']
        for i in  range(len(feature)):
            print(feature_name[i],':',feature[i])
        print("\n" )
        most_impotant = feature_name[np.argmax(feature)]
        print('for {}, the most important feature is "{}"'.format(model_name,  most_impotant))
    except:
        pass
    print('------------------------------------------------------------------------')

for model, model_name in zip(models, model_names):
    train_and_get_importance2(model, model_name)

Perceptron----traning
Misclassified samples: 154
Accuracy: 0.68
              precision    recall  f1-score   support

           0       0.54      0.61      0.57       169
           1       0.77      0.72      0.75       315

    accuracy                           0.68       484
   macro avg       0.66      0.67      0.66       484
weighted avg       0.69      0.68      0.69       484

[[103  66]
 [ 88 227]]
auc score 0.6650511881281113
------------------------------------------------------------------------
LogisticRegression----traning
Misclassified samples: 136
Accuracy: 0.72
              precision    recall  f1-score   support

           0       0.63      0.46      0.53       169
           1       0.75      0.86      0.80       315

    accuracy                           0.72       484
   macro avg       0.69      0.66      0.67       484
weighted avg       0.71      0.72      0.71       484

[[ 78  91]
 [ 45 270]]
auc score 0.6593406593406593
---------------------------------

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


Misclassified samples: 130
Accuracy: 0.73
              precision    recall  f1-score   support

           0       0.61      0.65      0.63       169
           1       0.81      0.77      0.79       315

    accuracy                           0.73       484
   macro avg       0.71      0.71      0.71       484
weighted avg       0.74      0.73      0.73       484

[[110  59]
 [ 71 244]]
auc score 0.7127453742838358
------------------------------------------------------------------------
KNN----traning
Misclassified samples: 144
Accuracy: 0.70
              precision    recall  f1-score   support

           0       0.58      0.53      0.55       169
           1       0.76      0.80      0.78       315

    accuracy                           0.70       484
   macro avg       0.67      0.66      0.66       484
weighted avg       0.70      0.70      0.70       484

[[ 89  80]
 [ 64 251]]
auc score 0.661726307880154
-----------------------------------------------------------------------